name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Sync Code
        uses: actions/checkout@v4

      - name: 2. Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 3. Install All Dependencies (The Good Stuff)
        run: npm install

      - name: 4. The Integrity Check (Build)
        run: npm run build

      - name: 5. Deploy to Web
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # This is where the functional code lives after the build
          branch: gh-pages
